version: "3.8"
services:
  controller:
    image: ngrinder/controller
    restart: always
    ports:
      - "9000:80"
      - "16001:16001"
      - "12000-12009:12000-12009"
    deploy:
      resources:
        limits:
          cpus : '2'
          memory: 4G

  agent:
    image: ngrinder/agent
    restart: always
    links:
      - controller
    deploy:
      resources:
        limits:
          cpus : '4'
          memory: 4G
