server:
  port: 0

spring:
  application:
    name: user-service

eureka:
  instance:
    # 인스턴스 아이디 등록
    instance-id: ${spirng.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
  client:
    # 레지스트리에 자신을 등록할지에 대한 여부
    register-with-eureka: true
    # 유레카에 registry 에 등록할지 여부
    fetch-registry: true
    service-url:
      # 주소
      defaultZone: http://127.0.0.1:8761/eureka


greeting:
  message: Welcome to the Simple E-commerce
